/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateSubagentRouteImport } from './routes/activate-subagent'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCheckersRouteImport } from './routes/admin.checkers'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as SSlugBecomeAgentRouteImport } from './routes/s.$slug.become-agent'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard/wallet'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard/transactions'
import { Route as AuthenticatedDashboardStoreRouteImport } from './routes/_authenticated/dashboard/store'
import { Route as AuthenticatedDashboardReportRouteImport } from './routes/_authenticated/dashboard/report'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardDeveloperRouteImport } from './routes/_authenticated/dashboard/developer'
import { Route as AuthenticatedDashboardCheckersRouteImport } from './routes/_authenticated/dashboard/checkers'
import { Route as AuthenticatedDashboardStoreIndexRouteImport } from './routes/_authenticated/dashboard/store.index'
import { Route as ApiPublicV1PaystackWebhookRouteImport } from './routes/api/public/v1/paystack-webhook'
import { Route as ApiPublicV1BalanceRouteImport } from './routes/api/public/v1/balance'
import { Route as AuthenticatedDashboardStoreWithdrawalsRouteImport } from './routes/_authenticated/dashboard/store.withdrawals'
import { Route as AuthenticatedDashboardStoreTransactionsRouteImport } from './routes/_authenticated/dashboard/store.transactions'
import { Route as AuthenticatedDashboardStoreSubagentsRouteImport } from './routes/_authenticated/dashboard/store.subagents'
import { Route as AuthenticatedDashboardStoreSettingsRouteImport } from './routes/_authenticated/dashboard/store.settings'
import { Route as AuthenticatedDashboardStorePackagesRouteImport } from './routes/_authenticated/dashboard/store.packages'
import { Route as AuthenticatedDashboardBuyDataNetworkRouteImport } from './routes/_authenticated/dashboard/buy-data/$network'
import { Route as ApiPublicV1TransactionsIdRouteImport } from './routes/api/public/v1/transactions.$id'
import { Route as ApiPublicV1StoreOrderVerifyRouteImport } from './routes/api/public/v1/store-order.verify'
import { Route as ApiPublicV1StoreOrderInitRouteImport } from './routes/api/public/v1/store-order.init'
import { Route as ApiPublicV1DataPurchaseRouteImport } from './routes/api/public/v1/data.purchase'
import { Route as ApiPublicV1CheckersPurchaseRouteImport } from './routes/api/public/v1/checkers.purchase'
import { Route as ApiPublicV1ActivationVerifyRouteImport } from './routes/api/public/v1/activation.verify'
import { Route as ApiPublicV1ActivationInitRouteImport } from './routes/api/public/v1/activation.init'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateSubagentRoute = ActivateSubagentRouteImport.update({
  id: '/activate-subagent',
  path: '/activate-subagent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckersRoute = AdminCheckersRouteImport.update({
  id: '/checkers',
  path: '/checkers',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SSlugBecomeAgentRoute = SSlugBecomeAgentRouteImport.update({
  id: '/become-agent',
  path: '/become-agent',
  getParentRoute: () => SSlugRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/dashboard/wallet',
    path: '/dashboard/wallet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/dashboard/transactions',
    path: '/dashboard/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardStoreRoute =
  AuthenticatedDashboardStoreRouteImport.update({
    id: '/dashboard/store',
    path: '/dashboard/store',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardReportRoute =
  AuthenticatedDashboardReportRouteImport.update({
    id: '/dashboard/report',
    path: '/dashboard/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardDeveloperRoute =
  AuthenticatedDashboardDeveloperRouteImport.update({
    id: '/dashboard/developer',
    path: '/dashboard/developer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCheckersRoute =
  AuthenticatedDashboardCheckersRouteImport.update({
    id: '/dashboard/checkers',
    path: '/dashboard/checkers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardStoreIndexRoute =
  AuthenticatedDashboardStoreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const ApiPublicV1PaystackWebhookRoute =
  ApiPublicV1PaystackWebhookRouteImport.update({
    id: '/api/public/v1/paystack-webhook',
    path: '/api/public/v1/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1BalanceRoute = ApiPublicV1BalanceRouteImport.update({
  id: '/api/public/v1/balance',
  path: '/api/public/v1/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardStoreWithdrawalsRoute =
  AuthenticatedDashboardStoreWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardStoreTransactionsRoute =
  AuthenticatedDashboardStoreTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardStoreSubagentsRoute =
  AuthenticatedDashboardStoreSubagentsRouteImport.update({
    id: '/subagents',
    path: '/subagents',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardStoreSettingsRoute =
  AuthenticatedDashboardStoreSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardStorePackagesRoute =
  AuthenticatedDashboardStorePackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedDashboardStoreRoute,
  } as any)
const AuthenticatedDashboardBuyDataNetworkRoute =
  AuthenticatedDashboardBuyDataNetworkRouteImport.update({
    id: '/dashboard/buy-data/$network',
    path: '/dashboard/buy-data/$network',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicV1TransactionsIdRoute =
  ApiPublicV1TransactionsIdRouteImport.update({
    id: '/api/public/v1/transactions/$id',
    path: '/api/public/v1/transactions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StoreOrderVerifyRoute =
  ApiPublicV1StoreOrderVerifyRouteImport.update({
    id: '/api/public/v1/store-order/verify',
    path: '/api/public/v1/store-order/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StoreOrderInitRoute =
  ApiPublicV1StoreOrderInitRouteImport.update({
    id: '/api/public/v1/store-order/init',
    path: '/api/public/v1/store-order/init',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1DataPurchaseRoute = ApiPublicV1DataPurchaseRouteImport.update({
  id: '/api/public/v1/data/purchase',
  path: '/api/public/v1/data/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CheckersPurchaseRoute =
  ApiPublicV1CheckersPurchaseRouteImport.update({
    id: '/api/public/v1/checkers/purchase',
    path: '/api/public/v1/checkers/purchase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ActivationVerifyRoute =
  ApiPublicV1ActivationVerifyRouteImport.update({
    id: '/api/public/v1/activation/verify',
    path: '/api/public/v1/activation/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ActivationInitRoute =
  ApiPublicV1ActivationInitRouteImport.update({
    id: '/api/public/v1/activation/init',
    path: '/api/public/v1/activation/init',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-subagent': typeof ActivateSubagentRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/checkers': typeof AdminCheckersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreRouteWithChildren
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/s/$slug/become-agent': typeof SSlugBecomeAgentRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/dashboard/store/packages': typeof AuthenticatedDashboardStorePackagesRoute
  '/dashboard/store/settings': typeof AuthenticatedDashboardStoreSettingsRoute
  '/dashboard/store/subagents': typeof AuthenticatedDashboardStoreSubagentsRoute
  '/dashboard/store/transactions': typeof AuthenticatedDashboardStoreTransactionsRoute
  '/dashboard/store/withdrawals': typeof AuthenticatedDashboardStoreWithdrawalsRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/paystack-webhook': typeof ApiPublicV1PaystackWebhookRoute
  '/dashboard/store/': typeof AuthenticatedDashboardStoreIndexRoute
  '/api/public/v1/activation/init': typeof ApiPublicV1ActivationInitRoute
  '/api/public/v1/activation/verify': typeof ApiPublicV1ActivationVerifyRoute
  '/api/public/v1/checkers/purchase': typeof ApiPublicV1CheckersPurchaseRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/store-order/init': typeof ApiPublicV1StoreOrderInitRoute
  '/api/public/v1/store-order/verify': typeof ApiPublicV1StoreOrderVerifyRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-subagent': typeof ActivateSubagentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/checkers': typeof AdminCheckersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/s/$slug/become-agent': typeof SSlugBecomeAgentRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/dashboard/store/packages': typeof AuthenticatedDashboardStorePackagesRoute
  '/dashboard/store/settings': typeof AuthenticatedDashboardStoreSettingsRoute
  '/dashboard/store/subagents': typeof AuthenticatedDashboardStoreSubagentsRoute
  '/dashboard/store/transactions': typeof AuthenticatedDashboardStoreTransactionsRoute
  '/dashboard/store/withdrawals': typeof AuthenticatedDashboardStoreWithdrawalsRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/paystack-webhook': typeof ApiPublicV1PaystackWebhookRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreIndexRoute
  '/api/public/v1/activation/init': typeof ApiPublicV1ActivationInitRoute
  '/api/public/v1/activation/verify': typeof ApiPublicV1ActivationVerifyRoute
  '/api/public/v1/checkers/purchase': typeof ApiPublicV1CheckersPurchaseRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/store-order/init': typeof ApiPublicV1StoreOrderInitRoute
  '/api/public/v1/store-order/verify': typeof ApiPublicV1StoreOrderVerifyRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/activate-subagent': typeof ActivateSubagentRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/checkers': typeof AdminCheckersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/_authenticated/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/_authenticated/dashboard/store': typeof AuthenticatedDashboardStoreRouteWithChildren
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/s/$slug/become-agent': typeof SSlugBecomeAgentRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/_authenticated/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/_authenticated/dashboard/store/packages': typeof AuthenticatedDashboardStorePackagesRoute
  '/_authenticated/dashboard/store/settings': typeof AuthenticatedDashboardStoreSettingsRoute
  '/_authenticated/dashboard/store/subagents': typeof AuthenticatedDashboardStoreSubagentsRoute
  '/_authenticated/dashboard/store/transactions': typeof AuthenticatedDashboardStoreTransactionsRoute
  '/_authenticated/dashboard/store/withdrawals': typeof AuthenticatedDashboardStoreWithdrawalsRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/paystack-webhook': typeof ApiPublicV1PaystackWebhookRoute
  '/_authenticated/dashboard/store/': typeof AuthenticatedDashboardStoreIndexRoute
  '/api/public/v1/activation/init': typeof ApiPublicV1ActivationInitRoute
  '/api/public/v1/activation/verify': typeof ApiPublicV1ActivationVerifyRoute
  '/api/public/v1/checkers/purchase': typeof ApiPublicV1CheckersPurchaseRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/store-order/init': typeof ApiPublicV1StoreOrderInitRoute
  '/api/public/v1/store-order/verify': typeof ApiPublicV1StoreOrderVerifyRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-subagent'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/checkers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/s/$slug'
    | '/admin/'
    | '/dashboard/checkers'
    | '/dashboard/developer'
    | '/dashboard/profile'
    | '/dashboard/report'
    | '/dashboard/store'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/admin/users/$userId'
    | '/s/$slug/become-agent'
    | '/dashboard/'
    | '/s/$slug/'
    | '/dashboard/buy-data/$network'
    | '/dashboard/store/packages'
    | '/dashboard/store/settings'
    | '/dashboard/store/subagents'
    | '/dashboard/store/transactions'
    | '/dashboard/store/withdrawals'
    | '/api/public/v1/balance'
    | '/api/public/v1/paystack-webhook'
    | '/dashboard/store/'
    | '/api/public/v1/activation/init'
    | '/api/public/v1/activation/verify'
    | '/api/public/v1/checkers/purchase'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/store-order/init'
    | '/api/public/v1/store-order/verify'
    | '/api/public/v1/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-subagent'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/checkers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/admin'
    | '/dashboard/checkers'
    | '/dashboard/developer'
    | '/dashboard/profile'
    | '/dashboard/report'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/admin/users/$userId'
    | '/s/$slug/become-agent'
    | '/dashboard'
    | '/s/$slug'
    | '/dashboard/buy-data/$network'
    | '/dashboard/store/packages'
    | '/dashboard/store/settings'
    | '/dashboard/store/subagents'
    | '/dashboard/store/transactions'
    | '/dashboard/store/withdrawals'
    | '/api/public/v1/balance'
    | '/api/public/v1/paystack-webhook'
    | '/dashboard/store'
    | '/api/public/v1/activation/init'
    | '/api/public/v1/activation/verify'
    | '/api/public/v1/checkers/purchase'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/store-order/init'
    | '/api/public/v1/store-order/verify'
    | '/api/public/v1/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate-subagent'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/checkers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/withdrawals'
    | '/s/$slug'
    | '/admin/'
    | '/_authenticated/dashboard/checkers'
    | '/_authenticated/dashboard/developer'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/report'
    | '/_authenticated/dashboard/store'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/wallet'
    | '/admin/users/$userId'
    | '/s/$slug/become-agent'
    | '/_authenticated/dashboard/'
    | '/s/$slug/'
    | '/_authenticated/dashboard/buy-data/$network'
    | '/_authenticated/dashboard/store/packages'
    | '/_authenticated/dashboard/store/settings'
    | '/_authenticated/dashboard/store/subagents'
    | '/_authenticated/dashboard/store/transactions'
    | '/_authenticated/dashboard/store/withdrawals'
    | '/api/public/v1/balance'
    | '/api/public/v1/paystack-webhook'
    | '/_authenticated/dashboard/store/'
    | '/api/public/v1/activation/init'
    | '/api/public/v1/activation/verify'
    | '/api/public/v1/checkers/purchase'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/store-order/init'
    | '/api/public/v1/store-order/verify'
    | '/api/public/v1/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivateSubagentRoute: typeof ActivateSubagentRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  ApiPublicV1BalanceRoute: typeof ApiPublicV1BalanceRoute
  ApiPublicV1PaystackWebhookRoute: typeof ApiPublicV1PaystackWebhookRoute
  ApiPublicV1ActivationInitRoute: typeof ApiPublicV1ActivationInitRoute
  ApiPublicV1ActivationVerifyRoute: typeof ApiPublicV1ActivationVerifyRoute
  ApiPublicV1CheckersPurchaseRoute: typeof ApiPublicV1CheckersPurchaseRoute
  ApiPublicV1DataPurchaseRoute: typeof ApiPublicV1DataPurchaseRoute
  ApiPublicV1StoreOrderInitRoute: typeof ApiPublicV1StoreOrderInitRoute
  ApiPublicV1StoreOrderVerifyRoute: typeof ApiPublicV1StoreOrderVerifyRoute
  ApiPublicV1TransactionsIdRoute: typeof ApiPublicV1TransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-subagent': {
      id: '/activate-subagent'
      path: '/activate-subagent'
      fullPath: '/activate-subagent'
      preLoaderRoute: typeof ActivateSubagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkers': {
      id: '/admin/checkers'
      path: '/checkers'
      fullPath: '/admin/checkers'
      preLoaderRoute: typeof AdminCheckersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$slug/become-agent': {
      id: '/s/$slug/become-agent'
      path: '/become-agent'
      fullPath: '/s/$slug/become-agent'
      preLoaderRoute: typeof SSlugBecomeAgentRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/store': {
      id: '/_authenticated/dashboard/store'
      path: '/dashboard/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof AuthenticatedDashboardStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/report': {
      id: '/_authenticated/dashboard/report'
      path: '/dashboard/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof AuthenticatedDashboardReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/developer': {
      id: '/_authenticated/dashboard/developer'
      path: '/dashboard/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/checkers': {
      id: '/_authenticated/dashboard/checkers'
      path: '/dashboard/checkers'
      fullPath: '/dashboard/checkers'
      preLoaderRoute: typeof AuthenticatedDashboardCheckersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/store/': {
      id: '/_authenticated/dashboard/store/'
      path: '/'
      fullPath: '/dashboard/store/'
      preLoaderRoute: typeof AuthenticatedDashboardStoreIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/api/public/v1/paystack-webhook': {
      id: '/api/public/v1/paystack-webhook'
      path: '/api/public/v1/paystack-webhook'
      fullPath: '/api/public/v1/paystack-webhook'
      preLoaderRoute: typeof ApiPublicV1PaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/balance': {
      id: '/api/public/v1/balance'
      path: '/api/public/v1/balance'
      fullPath: '/api/public/v1/balance'
      preLoaderRoute: typeof ApiPublicV1BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/store/withdrawals': {
      id: '/_authenticated/dashboard/store/withdrawals'
      path: '/withdrawals'
      fullPath: '/dashboard/store/withdrawals'
      preLoaderRoute: typeof AuthenticatedDashboardStoreWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/store/transactions': {
      id: '/_authenticated/dashboard/store/transactions'
      path: '/transactions'
      fullPath: '/dashboard/store/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardStoreTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/store/subagents': {
      id: '/_authenticated/dashboard/store/subagents'
      path: '/subagents'
      fullPath: '/dashboard/store/subagents'
      preLoaderRoute: typeof AuthenticatedDashboardStoreSubagentsRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/store/settings': {
      id: '/_authenticated/dashboard/store/settings'
      path: '/settings'
      fullPath: '/dashboard/store/settings'
      preLoaderRoute: typeof AuthenticatedDashboardStoreSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/store/packages': {
      id: '/_authenticated/dashboard/store/packages'
      path: '/packages'
      fullPath: '/dashboard/store/packages'
      preLoaderRoute: typeof AuthenticatedDashboardStorePackagesRouteImport
      parentRoute: typeof AuthenticatedDashboardStoreRoute
    }
    '/_authenticated/dashboard/buy-data/$network': {
      id: '/_authenticated/dashboard/buy-data/$network'
      path: '/dashboard/buy-data/$network'
      fullPath: '/dashboard/buy-data/$network'
      preLoaderRoute: typeof AuthenticatedDashboardBuyDataNetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/transactions/$id': {
      id: '/api/public/v1/transactions/$id'
      path: '/api/public/v1/transactions/$id'
      fullPath: '/api/public/v1/transactions/$id'
      preLoaderRoute: typeof ApiPublicV1TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/store-order/verify': {
      id: '/api/public/v1/store-order/verify'
      path: '/api/public/v1/store-order/verify'
      fullPath: '/api/public/v1/store-order/verify'
      preLoaderRoute: typeof ApiPublicV1StoreOrderVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/store-order/init': {
      id: '/api/public/v1/store-order/init'
      path: '/api/public/v1/store-order/init'
      fullPath: '/api/public/v1/store-order/init'
      preLoaderRoute: typeof ApiPublicV1StoreOrderInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/data/purchase': {
      id: '/api/public/v1/data/purchase'
      path: '/api/public/v1/data/purchase'
      fullPath: '/api/public/v1/data/purchase'
      preLoaderRoute: typeof ApiPublicV1DataPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/checkers/purchase': {
      id: '/api/public/v1/checkers/purchase'
      path: '/api/public/v1/checkers/purchase'
      fullPath: '/api/public/v1/checkers/purchase'
      preLoaderRoute: typeof ApiPublicV1CheckersPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/activation/verify': {
      id: '/api/public/v1/activation/verify'
      path: '/api/public/v1/activation/verify'
      fullPath: '/api/public/v1/activation/verify'
      preLoaderRoute: typeof ApiPublicV1ActivationVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/activation/init': {
      id: '/api/public/v1/activation/init'
      path: '/api/public/v1/activation/init'
      fullPath: '/api/public/v1/activation/init'
      preLoaderRoute: typeof ApiPublicV1ActivationInitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardStoreRouteChildren {
  AuthenticatedDashboardStorePackagesRoute: typeof AuthenticatedDashboardStorePackagesRoute
  AuthenticatedDashboardStoreSettingsRoute: typeof AuthenticatedDashboardStoreSettingsRoute
  AuthenticatedDashboardStoreSubagentsRoute: typeof AuthenticatedDashboardStoreSubagentsRoute
  AuthenticatedDashboardStoreTransactionsRoute: typeof AuthenticatedDashboardStoreTransactionsRoute
  AuthenticatedDashboardStoreWithdrawalsRoute: typeof AuthenticatedDashboardStoreWithdrawalsRoute
  AuthenticatedDashboardStoreIndexRoute: typeof AuthenticatedDashboardStoreIndexRoute
}

const AuthenticatedDashboardStoreRouteChildren: AuthenticatedDashboardStoreRouteChildren =
  {
    AuthenticatedDashboardStorePackagesRoute:
      AuthenticatedDashboardStorePackagesRoute,
    AuthenticatedDashboardStoreSettingsRoute:
      AuthenticatedDashboardStoreSettingsRoute,
    AuthenticatedDashboardStoreSubagentsRoute:
      AuthenticatedDashboardStoreSubagentsRoute,
    AuthenticatedDashboardStoreTransactionsRoute:
      AuthenticatedDashboardStoreTransactionsRoute,
    AuthenticatedDashboardStoreWithdrawalsRoute:
      AuthenticatedDashboardStoreWithdrawalsRoute,
    AuthenticatedDashboardStoreIndexRoute:
      AuthenticatedDashboardStoreIndexRoute,
  }

const AuthenticatedDashboardStoreRouteWithChildren =
  AuthenticatedDashboardStoreRoute._addFileChildren(
    AuthenticatedDashboardStoreRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardCheckersRoute: typeof AuthenticatedDashboardCheckersRoute
  AuthenticatedDashboardDeveloperRoute: typeof AuthenticatedDashboardDeveloperRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardReportRoute: typeof AuthenticatedDashboardReportRoute
  AuthenticatedDashboardStoreRoute: typeof AuthenticatedDashboardStoreRouteWithChildren
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBuyDataNetworkRoute: typeof AuthenticatedDashboardBuyDataNetworkRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardCheckersRoute: AuthenticatedDashboardCheckersRoute,
  AuthenticatedDashboardDeveloperRoute: AuthenticatedDashboardDeveloperRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardReportRoute: AuthenticatedDashboardReportRoute,
  AuthenticatedDashboardStoreRoute:
    AuthenticatedDashboardStoreRouteWithChildren,
  AuthenticatedDashboardTransactionsRoute:
    AuthenticatedDashboardTransactionsRoute,
  AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardBuyDataNetworkRoute:
    AuthenticatedDashboardBuyDataNetworkRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminCheckersRoute: typeof AdminCheckersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCheckersRoute: AdminCheckersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SSlugRouteChildren {
  SSlugBecomeAgentRoute: typeof SSlugBecomeAgentRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugBecomeAgentRoute: SSlugBecomeAgentRoute,
  SSlugIndexRoute: SSlugIndexRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivateSubagentRoute: ActivateSubagentRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SSlugRoute: SSlugRouteWithChildren,
  ApiPublicV1BalanceRoute: ApiPublicV1BalanceRoute,
  ApiPublicV1PaystackWebhookRoute: ApiPublicV1PaystackWebhookRoute,
  ApiPublicV1ActivationInitRoute: ApiPublicV1ActivationInitRoute,
  ApiPublicV1ActivationVerifyRoute: ApiPublicV1ActivationVerifyRoute,
  ApiPublicV1CheckersPurchaseRoute: ApiPublicV1CheckersPurchaseRoute,
  ApiPublicV1DataPurchaseRoute: ApiPublicV1DataPurchaseRoute,
  ApiPublicV1StoreOrderInitRoute: ApiPublicV1StoreOrderInitRoute,
  ApiPublicV1StoreOrderVerifyRoute: ApiPublicV1StoreOrderVerifyRoute,
  ApiPublicV1TransactionsIdRoute: ApiPublicV1TransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
