/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard/wallet'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard/transactions'
import { Route as AuthenticatedDashboardStoreRouteImport } from './routes/_authenticated/dashboard/store'
import { Route as AuthenticatedDashboardReportRouteImport } from './routes/_authenticated/dashboard/report'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardDeveloperRouteImport } from './routes/_authenticated/dashboard/developer'
import { Route as AuthenticatedDashboardCheckersRouteImport } from './routes/_authenticated/dashboard/checkers'
import { Route as ApiPublicV1BalanceRouteImport } from './routes/api/public/v1/balance'
import { Route as AuthenticatedDashboardBuyDataNetworkRouteImport } from './routes/_authenticated/dashboard/buy-data/$network'
import { Route as ApiPublicV1TransactionsIdRouteImport } from './routes/api/public/v1/transactions.$id'
import { Route as ApiPublicV1DataPurchaseRouteImport } from './routes/api/public/v1/data.purchase'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStoreRoute =
  AuthenticatedDashboardStoreRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportRoute =
  AuthenticatedDashboardReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDeveloperRoute =
  AuthenticatedDashboardDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCheckersRoute =
  AuthenticatedDashboardCheckersRouteImport.update({
    id: '/checkers',
    path: '/checkers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicV1BalanceRoute = ApiPublicV1BalanceRouteImport.update({
  id: '/api/public/v1/balance',
  path: '/api/public/v1/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardBuyDataNetworkRoute =
  AuthenticatedDashboardBuyDataNetworkRouteImport.update({
    id: '/buy-data/$network',
    path: '/buy-data/$network',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicV1TransactionsIdRoute =
  ApiPublicV1TransactionsIdRouteImport.update({
    id: '/api/public/v1/transactions/$id',
    path: '/api/public/v1/transactions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1DataPurchaseRoute = ApiPublicV1DataPurchaseRouteImport.update({
  id: '/api/public/v1/data/purchase',
  path: '/api/public/v1/data/purchase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/dashboard/store': typeof AuthenticatedDashboardStoreRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/dashboard/checkers': typeof AuthenticatedDashboardCheckersRoute
  '/_authenticated/dashboard/developer': typeof AuthenticatedDashboardDeveloperRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/report': typeof AuthenticatedDashboardReportRoute
  '/_authenticated/dashboard/store': typeof AuthenticatedDashboardStoreRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/dashboard/buy-data/$network': typeof AuthenticatedDashboardBuyDataNetworkRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/data/purchase': typeof ApiPublicV1DataPurchaseRoute
  '/api/public/v1/transactions/$id': typeof ApiPublicV1TransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/s/$slug'
    | '/dashboard/checkers'
    | '/dashboard/developer'
    | '/dashboard/profile'
    | '/dashboard/report'
    | '/dashboard/store'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/dashboard/buy-data/$network'
    | '/api/public/v1/balance'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/s/$slug'
    | '/dashboard/checkers'
    | '/dashboard/developer'
    | '/dashboard/profile'
    | '/dashboard/report'
    | '/dashboard/store'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/dashboard/buy-data/$network'
    | '/api/public/v1/balance'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/s/$slug'
    | '/_authenticated/dashboard/checkers'
    | '/_authenticated/dashboard/developer'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/report'
    | '/_authenticated/dashboard/store'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/dashboard/buy-data/$network'
    | '/api/public/v1/balance'
    | '/api/public/v1/data/purchase'
    | '/api/public/v1/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicV1BalanceRoute: typeof ApiPublicV1BalanceRoute
  ApiPublicV1DataPurchaseRoute: typeof ApiPublicV1DataPurchaseRoute
  ApiPublicV1TransactionsIdRoute: typeof ApiPublicV1TransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/store': {
      id: '/_authenticated/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof AuthenticatedDashboardStoreRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/report': {
      id: '/_authenticated/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof AuthenticatedDashboardReportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/developer': {
      id: '/_authenticated/dashboard/developer'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/checkers': {
      id: '/_authenticated/dashboard/checkers'
      path: '/checkers'
      fullPath: '/dashboard/checkers'
      preLoaderRoute: typeof AuthenticatedDashboardCheckersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/v1/balance': {
      id: '/api/public/v1/balance'
      path: '/api/public/v1/balance'
      fullPath: '/api/public/v1/balance'
      preLoaderRoute: typeof ApiPublicV1BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/buy-data/$network': {
      id: '/_authenticated/dashboard/buy-data/$network'
      path: '/buy-data/$network'
      fullPath: '/dashboard/buy-data/$network'
      preLoaderRoute: typeof AuthenticatedDashboardBuyDataNetworkRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/v1/transactions/$id': {
      id: '/api/public/v1/transactions/$id'
      path: '/api/public/v1/transactions/$id'
      fullPath: '/api/public/v1/transactions/$id'
      preLoaderRoute: typeof ApiPublicV1TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/data/purchase': {
      id: '/api/public/v1/data/purchase'
      path: '/api/public/v1/data/purchase'
      fullPath: '/api/public/v1/data/purchase'
      preLoaderRoute: typeof ApiPublicV1DataPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCheckersRoute: typeof AuthenticatedDashboardCheckersRoute
  AuthenticatedDashboardDeveloperRoute: typeof AuthenticatedDashboardDeveloperRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardReportRoute: typeof AuthenticatedDashboardReportRoute
  AuthenticatedDashboardStoreRoute: typeof AuthenticatedDashboardStoreRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardBuyDataNetworkRoute: typeof AuthenticatedDashboardBuyDataNetworkRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCheckersRoute: AuthenticatedDashboardCheckersRoute,
    AuthenticatedDashboardDeveloperRoute: AuthenticatedDashboardDeveloperRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardReportRoute: AuthenticatedDashboardReportRoute,
    AuthenticatedDashboardStoreRoute: AuthenticatedDashboardStoreRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardBuyDataNetworkRoute:
      AuthenticatedDashboardBuyDataNetworkRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicV1BalanceRoute: ApiPublicV1BalanceRoute,
  ApiPublicV1DataPurchaseRoute: ApiPublicV1DataPurchaseRoute,
  ApiPublicV1TransactionsIdRoute: ApiPublicV1TransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
